#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9'

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
#~/.config/polybar/launch.sh &

# Run EWW.
$HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi
    if [ "$flag" == on ]; then
        $HOME/.local/bin/eww -c $HOME/.config/eww/bar close-all
  else
        $HOME/.local/bin/eww -c $HOME/.config/eww/bar open bar
    fi
done &

# bspc config left_padding 45

# Notifications
#/usr/bin/dunst &

# Run notification daemon.
dunst --config $HOME/.config/dunst/dunstrc &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
# nitrogen --restore &
# feh --bg-fill ~/Wallpapers/waves.png
# feh --bg-fill ~/Wallpapers/supercar.jpg
# feh --bg-fill ~/Wallpapers/city_sunset.jpg
# feh --bg-fill ~/Wallpapers/pixel_earth.jpg
# feh --bg-fill ~/Wallpapers/hill.png
# feh --bg-fill ~/Wallpapers/supercar_3.png
# feh --bg-fill ~/Wallpapers/wavesRightColored.png
# feh --bg-fill ~/Wallpapers/japan-Macchiato.jpg
# feh --bg-fill ~/Wallpapers/mountain_ani.png
# feh --bg-fill ~/Wallpapers/ufo_pixel.jpg
# feh --bg-fill ~/Wallpapers/sam_tori_gate.jpg
# feh --bg-fill ~/Wallpapers/sunset.jpg
# feh --bg-fill ~/Wallpapers/car_ani.png
# feh --bg-fill ~/Wallpapers/car_ani_crop.png
feh --bg-fill ~/Wallpapers/Evermore-catppuccin.png
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
# picom -b &
picom --config $HOME/.config/picom/picom.conf &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

